import { Geist, Geist_Mono } from "next/font/google";
import { LoaderProvider } from "@/context/loader/loader.contex";
import { AuthProvider } from "@/context/auth/auth.context";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <LoaderProvider>
            <Navbar />
            {children}
          </LoaderProvider>
        </AuthProvider>
      </body>
    </html>
  );
}